dist: bionic
language: python
python:
- '3.7'
install:
- pip install pipenv
- pipenv install --dev
script: make test-coverage-upload
env:
  global:
    secure: aafNNNCC1hgtoYclnR6sDOY+GAXpFwTSv8NDmwE+c7/PlHZK7LtvmX7HRXZzgOYxa0rNdOVyu1ptqOC0VEbwvIr5dDqrgKB4ARplGlkWEAeC/7sUiJZiVuEozVgabscOW2j8pg7fOBXualehM/+pDhSYE5ba5mmBGvhcWatG+x59U5gEJBJolIZ3VML0VfANEX+zQQIRWUq7l0dlY5TJnMmeobj4FnBxw7sT7CEYbXNsv7pTZ5DkJ+GyQI35ekSTVhptaKzh/0W4QGKdgSqRXbztnIoOGI9AOVoqeqEoeflVvFn/SdIw9j9DrTNhUNPyedssxGAjOy2WG/b/wN3OyveFfuLdGDPn1rLoANA67D9xtwmEWPA9U1XqhSc49rXPEjuCL31G1R11bCjbq06k8DUDcVCf0qZf572J9riJt4IR51kaDyqlXGm5cvaeTUEaw4VmYx1vNNVcsHjSfNkHlUgdP9DOp7nVkGkg8WQsJUAA6f1akQ0hamuGGkedt8hFmfrMwhNZiZTjp4WyfwbC8OrcUK5hys72srQfUFhcl0RBFVZwk+ZkaM5lfFVaCp+Hj4nBfTH40S4PQJQ8Jj2UsDD/FeJb7l+J042Myd0kwFui85wMtpZDHoFcSpxBYVji5Mqis8bzMn6CIyw+YnTVqsKeFDmsHwH59EhG4S5eA3o=
